[package]
name = "rrud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.8.2"
rocket = "0.5.1"
serde = "1.0.203"
serde_json = "1.0.117"
